In [1]:
from pool_generation import poolGeneration
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

X,y = load_wine(return_X_y=True, as_frame=False)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)


pool = poolGeneration()
pool.nr_generation = 2

pool.generate(X_train, y_train, X_test, y_test, 4)

bags = pool.get_bags()

0
gen	nevals
0  	100   
1  	100   
2  	100   
1


C:\Users\mathe\AppData\Roaming\Python\Python311\site-packages\deap\creator.py:138: RuntimeWarning: A class named 'FitnessMult' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "
C:\Users\mathe\AppData\Roaming\Python\Python311\site-packages\deap\creator.py:138: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "


gen	nevals
0  	100   
1  	100   
2  	100   
2


C:\Users\mathe\AppData\Roaming\Python\Python311\site-packages\deap\creator.py:138: RuntimeWarning: A class named 'FitnessMult' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "
C:\Users\mathe\AppData\Roaming\Python\Python311\site-packages\deap\creator.py:138: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "


gen	nevals
0  	100   
1  	100   
2  	100   
3


C:\Users\mathe\AppData\Roaming\Python\Python311\site-packages\deap\creator.py:138: RuntimeWarning: A class named 'FitnessMult' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "
C:\Users\mathe\AppData\Roaming\Python\Python311\site-packages\deap\creator.py:138: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  warnings.warn("A class named '{0}' has already been created and it "


gen	nevals
0  	100   
1  	100   
2  	100   


In [1]:
from pool_generation import poolGeneration
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

X,y = load_wine(return_X_y=True, as_frame=False)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)


pool = poolGeneration()

grupos = ["overlapping", "neighborhood", "linearity", "dimensionality", "balance", "network"]

pool.vote_complexity( X_train, y_train, grupos)

TypeError: only size-1 arrays can be converted to Python scalars

In [2]:
print(len(bags))

# -Seleção dinamica
# ola
# lca 
# rank

# -emsamble
# knora -> union/eliminate
# metades

# -voto majoritário

# deslib lib para fazer os testes

from deslib.des.knora_e import KNORAE
from sklearn.ensemble import RandomForestClassifier

# Train a pool of 10 classifiers
pool_classifiers = RandomForestClassifier(n_estimators=10)
pool_classifiers.fit(X_train, y_train)

# Initialize the DES model
knorae = KNORAE(pool_classifiers)

# Preprocess the Dynamic Selection dataset (DSEL)
knorae.fit(bags[0][0], bags[0][1])

print(X_test)
# Predict new examples:
knorae.predict(X_test)


400
[[1.364e+01 3.100e+00 2.560e+00 ... 9.600e-01 3.360e+00 8.450e+02]
 [1.421e+01 4.040e+00 2.440e+00 ... 8.700e-01 3.330e+00 1.080e+03]
 [1.293e+01 2.810e+00 2.700e+00 ... 7.700e-01 2.310e+00 6.000e+02]
 ...
 [1.285e+01 1.600e+00 2.520e+00 ... 1.090e+00 3.630e+00 1.015e+03]
 [1.281e+01 2.310e+00 2.400e+00 ... 6.600e-01 1.360e+00 5.600e+02]
 [1.272e+01 1.810e+00 2.200e+00 ... 1.160e+00 3.140e+00 7.140e+02]]


AttributeError: module 'numpy' has no attribute 'float'

In [5]:
import Cpx

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.5, random_state=42)
group = ["overlapping", 'neighborhood', '', '', '', '']
types = ["F1", 'T1', '', '', '', '']

cpx = Cpx.complexity_data3(X_val, y_val, group, types)

print(cpx)

[0.25592327790990027, 0.11111111111111112]


In [7]:
from sklearn.linear_model import Perceptron

clf = Perceptron(tol=1e-3, random_state=0)

# for bag in bags:
#     clf.fit(bag[0], bag[1])
clf.fit(bags[0][0], bags[0][1])    
# clf.fit(X_train, y_train)
clf.score(X_val, y_val)

0.24719101123595505

In [3]:
# for i in pool.bags_saved:
#     print(i)

print(bags[0])

([array([1.438e+01, 3.590e+00, 2.280e+00, 1.600e+01, 1.020e+02, 3.250e+00,
       3.170e+00, 2.700e-01, 2.190e+00, 4.900e+00, 1.040e+00, 3.440e+00,
       1.065e+03]), array([1.383e+01, 1.570e+00, 2.620e+00, 2.000e+01, 1.150e+02, 2.950e+00,
       3.400e+00, 4.000e-01, 1.720e+00, 6.600e+00, 1.130e+00, 2.570e+00,
       1.130e+03]), array([1.394e+01, 1.730e+00, 2.270e+00, 1.740e+01, 1.080e+02, 2.880e+00,
       3.540e+00, 3.200e-01, 2.080e+00, 8.900e+00, 1.120e+00, 3.100e+00,
       1.260e+03]), array([1.208e+01, 1.330e+00, 2.300e+00, 2.360e+01, 7.000e+01, 2.200e+00,
       1.590e+00, 4.200e-01, 1.380e+00, 1.740e+00, 1.070e+00, 3.210e+00,
       6.250e+02]), array([ 12.29,   3.17,   2.21,  18.  ,  88.  ,   2.85,   2.99,   0.45,
         2.81,   2.3 ,   1.42,   2.83, 406.  ]), array([1.422e+01, 3.990e+00, 2.510e+00, 1.320e+01, 1.280e+02, 3.000e+00,
       3.040e+00, 2.000e-01, 2.080e+00, 5.100e+00, 8.900e-01, 3.530e+00,
       7.600e+02]), array([1.251e+01, 1.240e+00, 2.250e+00, 1.750e+0